apiVersion: v2
name: opentelemetry-target-allocator
version: 0.158.1
description: OpenTelemetry Target Allocator Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/opentelemetry-operator
maintainers:
  - name: atoulme
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
appVersion: 0.158.0
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart source
      url: https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-target-allocator
    - name: Chart releases
      url: https://github.com/open-telemetry/opentelemetry-helm-charts/releases?q=opentelemetry-target-allocator&expanded=true
    - name: support
      url: https://github.com/open-telemetry/opentelemetry-helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: 809A5AC5DA08F79218A2962799CA262FF8EBBB9B
    url: https://open-telemetry.github.io/opentelemetry-helm-charts/pubkey.asc
