apiVersion: v2
name: opentelemetry-ebpf
version: 0.1.8
description: OpenTelemetry eBPF Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/opentelemetry-ebpf
maintainers:
  - name: dmitryax
  - name: jaronoff97
  - name: TylerHelmuth
  - name: nicolastakashi
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
appVersion: v0.10.2
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart source
      url: https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-ebpf
    - name: Chart releases
      url: https://github.com/open-telemetry/opentelemetry-helm-charts/releases?q=opentelemetry-ebpf&expanded=true
    - name: support
      url: https://github.com/open-telemetry/opentelemetry-helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: 809A5AC5DA08F79218A2962799CA262FF8EBBB9B
    url: https://open-telemetry.github.io/opentelemetry-helm-charts/pubkey.asc
